import type { Metadata } from "next";

import BackButton from "@/components/BackButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//TODO: reactnode 2개를 children으로 받을 수 있음???
export default function BackLayout({
  children,
  title,
  action
}: Readonly<{
  children: React.ReactNode;
  title: string;
  action?: React.ReactNode;
}>) {
  return (
    <div>
      <div className="flex items-center my-7 mx-5">
        <BackButton />
        <div className="flex-1 flex justify-center">
          <p className="text-2xl font-bold">{title}</p>
          {action}
        </div>
      </div>

      {children}
    </div>
  );
}
