import type { Metadata } from "next";
import '../globalIcon.css';
import BackButton from "@/components/BackButton";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BackLayout({
  children,
  title
}: Readonly<{
  children: React.ReactNode;
  title: string;
}>) {
  return (
    <div>
    <div className="relative flex flex-row items-center my-7 mx-5">
  <BackButton />
  <p className="absolute left-1/2 transform -translate-x-1/2 text-2xl font-bold">{title}</p>

</div>

      {children}
    </div>
    
  );
}