import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./globalIcon.css"
import StoreProvider from "./StoreProvider";
import { firebaseApp } from "@/libs/firebase";
import { getFirestore } from "firebase/firestore";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

getFirestore(firebaseApp);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
        {children}
        </StoreProvider>
        </body>
    </html>
  );
}